version: "3"
services:
  reverseproxy:
    build:
      context: .
    ports:
        - 80:80
    restart: always
    depends_on:
      - backend-todo     
  backend-todo:
    build:
      context: ../../k8s-restapi-todo 
    environment:
      TODOS_TABLE: $TODOS_TABLE
      USERS_TODO_TABLE: $USERS_TODO_TABLE 
      USERID_INDEX: $USERID_INDEX 
      TODOS_S3_BUCKET: $TODOS_S3_BUCKET 
      THUMBNAILS_S3_BUCKET: $THUMBNAILS_S3_BUCKET 
      SIGNED_URL_EXPIRATION: $SIGNED_URL_EXPIRATION 
      BUCKET_REGION: $BUCKET_REGION
      URL: $URL
  frontend:
    build:
      context: ../../client  
    ports:
      - "3000:3000"
